global_costmap:
  update_frequency: 0.5
  publish_frequency: 1.5
  transform_tolerance: 0.5
  width: 30
  height: 30
  origin_x: -15
  origin_y: -15
  static_map: false
  rolling_window: true
  inflation_radius: 2.5
  resolution: 0.01
