local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 2.5
  publish_frequency: 2.5
  transform_tolerance: 0.25
  static_map: false
  rolling_window: true
  width: 10
  height: 10
  origin_x: -5
  origin_y: -5
  resolution: 0.01
  # changed from 1.0 to 0.3
  inflation_radius: 0.3
