local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 2.5
  publish_frequency: 2.5
  transform_tolerance: 0.25
  static_map: false
  rolling_window: true
  width: 5
  height: 5
  origin_x: -2.5
  origin_y: -2.5
  resolution: 0.01
  # changed back to original 1.0 based on ROS navigation tuning guide
  # but it won't really matter for out case of no obstacles
  inflation_radius: 1.0
