TrajectoryPlannerROS:
 max_vel_x: 0.1
 min_vel_x: -0.1
 max_vel_theta: 2.5
 min_vel_theta: -2.5
 min_in_place_vel_theta: 0.5
 acc_lim_theta: 1.0
 acc_lim_x: 1.5
 acc_lim_Y: 1.5
 holonomic_robot: false
 meter_scoring: true
 xy_goal_tolerance: 0.1
 yaw_goal_tolerance: 0.1
 #occdist_scale:  0.01
 #pdist_scale: 0.4
 #gdist_scale: 0.2
 sim_time: 4.0
 latch_xy_goal_tolerance: true
 dwa: true

 vx_samples: 5
 vth_samples: 10
 #path_distance_bias: 32.0
 #goal_distance_bias: 20.0
 #occdist_scale: 0.02
 path_distance_bias: 2.0
 goal_distance_bias: 0.2
 occdist_scale: 0.01
 # use default sim_granularity value (granularity of steps between traj points)
 sim_granularity: 0.025
 publish_cost_grid_pc: true
 global_frame_id: odom
 prune_plan: true
 heading_lookahead: 0.325
 # If we are using DWA these will also be used:
 twirling_scale: 0.02
 # changing the oscillation reset angle back from 1.0 to default of 0.2
 oscillation_reset_angle: 1.0
